/**
 * N99 API
 * An API to do awesome things
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateSessionOfEducationDto { 
    name: string;
    month_start: string;
    month_end: string;
    date_opened_at: string;
    date_closed_at: string;
    is_active: boolean;
}

