/**
 * N99 API
 * An API to do awesome things
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateStudentDto { 
    first_name?: string;
    last_name?: string;
    age?: number;
    ville?: string;
    quartier?: string;
    telephone?: string;
    adresse?: string;
    dob?: string;
    nationality?: string;
    photo?: string;
}

