/**
 * N99 API
 * An API to do awesome things
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserDto { 
    first_name: string;
    last_name: string;
    email: string;
    password: string;
    /**
     * Has to match a regular expression: /^\\+[1-9]\\d{1,14}$/
     */
    phone: string;
    country?: string;
    city?: string;
    siren?: string;
    role?: string;
    status?: boolean;
}

